# House price Prediction procject ( dự án  : Dự đoán giá nhà )
* Goal : predict the sales price for each house 

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [2]:
data_df = pd.read_csv("train.csv")
data_df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [4]:
# ta thấy Id và số thứ tự bị trùng ( cần 1 cái là được )
data_df = pd.read_csv("train.csv",index_col="Id")
data_df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [5]:
# Có tổng cộng 80 cột thì ta cần xem gồm những cột nào : 
data_df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

In [6]:
# Choose features to train ML model ( chọn ra các cột cần thiết để train mô hình ML)

In [7]:
features = ["LotArea","YearBuilt","1stFlrSF","2ndFlrSF","FullBath","BedroomAbvGr","TotRmsAbvGrd"]


### 3 Spliting dataset into X and Y 

In [70]:
x = data_df[features]
x

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                     
1        8450       2003       856       854         2             3   
2        9600       1976      1262         0         2             3   
3       11250       2001       920       866         2             3   
4        9550       1915       961       756         1             3   
5       14260       2000      1145      1053         2             4   
...       ...        ...       ...       ...       ...           ...   
1456     7917       1999       953       694         2             3   
1457    13175       1978      2073         0         2             3   
1458     9042       1941      1188      1152         2             4   
1459     9717       1950      1078         0         1             2   
1460     9937       1965      1256         0         1             3   

      TotRmsAbvGrd  
Id                  
1                8  
2                6  
3                6  
4                7  
5                9  
...            ...  
1456             7  
1457             7  
1458             9  
1459             5  
1460             6  

[1460 rows x 7 columns]

In [71]:
y = data_df.iloc[:,-1]
y

Id
1       208500
2       181500
3       223500
4       140000
5       250000
         ...  
1456    175000
1457    210000
1458    266500
1459    142125
1460    147500
Name: SalePrice, Length: 1460, dtype: int64

In [72]:
from sklearn.model_selection import train_test_split 
np.random.seed(0)
Xtrain,Xtest,Ytrain,Ytest =train_test_split(x,y,test_size=0.2,train_size=0.8,random_state=0)
Xtrain 

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                     
619     11694       2007      1828         0         2             3   
871      6600       1962       894         0         1             2   
93      13360       1921       964         0         1             2   
818     13265       2002      1689         0         2             3   
303     13704       2001      1541         0         2             3   
...       ...        ...       ...       ...       ...           ...   
764      9430       1999      1268      1097         2             3   
836      9600       1950      1067         0         2             2   
1217     8930       1978      1318       584         2             4   
560      3196       2003      1557         0         2             2   
685     16770       1998      1195       644         2             4   

      TotRmsAbvGrd  
Id                  
619              9  
871              5  
93               5  
818              7  
303              6  
...            ...  
764              8  
836              4  
1217             8  
560              7  
685              7  

[1168 rows x 7 columns]

In [73]:
Xtest

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                     
530     32668       1957      2515         0         3             4   
492      9490       1941       958       620         1             3   
460      7015       1950       979       224         1             3   
280     10005       1977      1156       866         2             4   
656      1680       1971       525       567         1             3   
...       ...        ...       ...       ...       ...           ...   
327     10846       1993      1719         0         1             1   
441     15431       2008      2402         0         2             2   
1388     8520       1916      1664       862         2             5   
1324     5330       1940       708         0         1             2   
62       7200       1920       581       530         1             3   

      TotRmsAbvGrd  
Id                  
530              9  
492              5  
460              5  
280              8  
656              6  
...            ...  
327              6  
441             10  
1388            10  
1324             5  
62               6  

[292 rows x 7 columns]

In [74]:
Ytrain

Id
619     314813
871     109500
93      163500
818     271000
303     205000
         ...  
764     337000
836     128000
1217    112000
560     234000
685     221000
Name: SalePrice, Length: 1168, dtype: int64

In [75]:
Ytest

Id
530     200624
492     133000
460     110000
280     192000
656      88000
         ...  
327     324000
441     555000
1388    136000
1324     82500
62      101000
Name: SalePrice, Length: 292, dtype: int64

### 4 Train Model :

In [76]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(random_state=1)
# dt là 1 mô hình rỗng , giờ ta cần đưa dữ liệu : 
dt.fit(Xtrain,Ytrain)

DecisionTreeRegressor(random_state=1)

In [78]:
# ta đã có được 1 mô hình đơn giản , giờ ta tiến hành dự đoán : 
y_predict = dt.predict(Xtest.head())
y_predict

array([335000., 140200., 119000., 207500., 112000.])

In [79]:
pd.DataFrame({'ytest':Ytest.head() , 'ypredict':y_predict})

ytest  ypredict
Id                   
530  200624  335000.0
492  133000  140200.0
460  110000  119000.0
280  192000  207500.0
656   88000  112000.0

In [80]:
from sklearn.ensemble import RandomForestRegressor , GradientBoostingRegressor

In [83]:
rf_model=RandomForestRegressor(random_state=1) # Mô hình này dùng để test hết dữ liệu phần Xtest để dự đoán 

In [84]:
rf_model.fit(Xtrain,Ytrain)

RandomForestRegressor(random_state=1)

In [87]:
rf_predict=rf_model.predict(Xtest)
rf_predict[:5]

array([271690., 155039., 122024., 188915.,  91147.])

In [88]:
# Bây giờ chỉ lấy dữ liệu của 1 ngôi nhà duy nhất để đưa ra dự đoán : 
Xtest

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                     
530     32668       1957      2515         0         3             4   
492      9490       1941       958       620         1             3   
460      7015       1950       979       224         1             3   
280     10005       1977      1156       866         2             4   
656      1680       1971       525       567         1             3   
...       ...        ...       ...       ...       ...           ...   
327     10846       1993      1719         0         1             1   
441     15431       2008      2402         0         2             2   
1388     8520       1916      1664       862         2             5   
1324     5330       1940       708         0         1             2   
62       7200       1920       581       530         1             3   

      TotRmsAbvGrd  
Id                  
530              9  
492              5  
460              5  
280              8  
656              6  
...            ...  
327              6  
441             10  
1388            10  
1324             5  
62               6  

[292 rows x 7 columns]

In [90]:
# đưa dự đoán ứng với các cột ( dữ liệu mảng 2 chiều nên có 2 dấu ngoặc [[]])
rf_model.predict([[6969,2021,1000,800,4,5,9]])

D:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([215379.83])

In [ ]:
# Hỏi mô hình chính xác bao nhiêu phần trăm ( bài sau nha )